other2other_instructions = {
    "speech2speech" : [
        "Response to the speech with a speech that is contextually appropriate.",
        "Respond with a speech that semantically matches the speech provided.",
        "Please respond with a speech that corresponds to the speech.",
        "Generate a speech response that aligns with the meaning of the speech.",
        "Based on the speech provided, respond with a relevant speech.",
        "What would be a suitable speech to respond to the speech? Generate a corresponding speech.",
        "Match the speech with a meaningful response speech.",
        "Respond verbally with a statement that reflects the essence of the given speech.",
        "Produce a conversational response that matches the sentiment of the speech provided.",
        "Generate a spoken response that is contextually appropriate.",
        "Deliver a spoken answer that encapsulates the ideas presented in the preceding speech.",
        "Craft a speech response that semantically corresponds with the initial statement.",
        "Respond with a verbal reply that resonates with the core message of the provided speech.",
        "Create an oral reply that reflects the intent and meaning of the given speech",
        "Generate a spoken statement that harmonizes with the context of the preceding dialogue.",
        "Deliver a speech that conveys a similar meaning to the one provided.",
        "Produce a verbal response that captures the essence of the original speech.",
        "Create a spoken reply that mirrors the thoughts expressed in the previous speech.",
        "Reply with a conversational response to the statement given.",
        "Provide a speech that reacts to the previous speech in everyday life.",
        "Craft a reply that addresses the earlier speech in a relatable way.",
        "Deliver a response that addresses the previous speech given.",
        "Craft a speech that directly replies to the last statement made.",
        "Respond in a speech format to the points raised in the prior address.",
        "Formulate a speech that acknowledges and responds to the last speaker's speech.",
        "Compose a speech that offers a different perspective on the last speech.",
        "Respond with a speech that replies to the previous speech.",
        "Deliver a speech that responds to the earlier statement.",
        "Formulate a speech that answers the previous remarks.",
        "Articulate a response in speech form to the last address.",
        "Generate a speech that reflects on the earlier speech.",
        "Craft a speech that replies directly to the previous speaker.",
        "Present a speech that acknowledges the last statement.",
        "Compose a speech that responds to the points made earlier.",
        "Prepare a speech that engages with the last speech given.",
        "Deliver a speech that interacts with the last address.",
        "Generate a speech that connects with the earlier speech.",
        "Articulate a speech that follows the previous discussion.",
        "Create a speech that responds to the last remarks.",
        "Compose a speech that replies to the earlier address.",
        "Prepare a speech that answers the last speaker's points.",
        "Formulate a speech that reacts to the previous speech.",
        "Craft a speech that engages with the last speaker's words.",
        "Deliver a speech that addresses what was just said.",
        "Respond in a speech format to the previous remarks.",
        "Generate a speech that connects to the last statement.",
        "Present a speech that follows up on the earlier address.",
        "Articulate a response that engages with the last discussion.",
        "Compose a speech that acknowledges the prior speech.",
        "Prepare a speech that addresses the last points made.",
        "Devise a speech that responds to the previous address.",
        "Craft a speech that follows the last speaker's comments.",
        "Deliver a speech that addresses the earlier speech.",
        "Generate a speech that reflects on the last remarks.",
        
    ],
    "motion2motion" : [
        "Response to the motion with a motion that is contextually appropriate.",
        "Respond with an action that semantically matches the motion provided.",
        "Please respond with a motion that corresponds to the movement.",
        "Generate a motion response that aligns with the meaning of the action.",
        "Based on the motion provided, respond with a relevant action.",
        "What would be a suitable action to respond to the motion? Generate a corresponding motion.",
        "Match the action with a meaningful response motion.",
        "React to your partner's movement with an appropriate action.",
        "Given the action, create a motion response that fits the context.",
        "Create a motion that logically follows the action.",
        "Provide a semantically aligned motion in response to the action.",
        "Respond to the motion with an action that makes sense in the given context.",
        "Generate a motion that corresponds to the action.",
        "React to the movement with a motion that fits the context.",
        "Generate a motion that is a suitable response to the action.",
        "Respond to the action with a motion that is contextually appropriate.",
        "Create a motion that is a logical response to the action.",
        "Produce a follow-up motion that is coherent with the movement.",
        "Generate a motion that is a fitting response to the action.",
        "Reflect the meaning of the motion by generating a relevant motion response.",
        "Based on the action, generate a motion that fits the interaction.",
        "Respond with a motion that naturally flows from the movement.",
        "Generate a motion that is a natural response to the action.",
        "Create a motion that corresponds to the action.",
        "Respond to the action with a motion that fits the context.",
        "Generate a motion that is a suitable response to the action.",
        "Respond with an action that acknowledges the previous movement.",
        "Perform an action that reflects the last gesture made.",
        "Create a response action that engages with the earlier motion.",
        "Deliver a movement that reacts to the last person's actions.",
        "Articulate a response through an action that follows the previous gesture.",
        "Generate an action that complements the earlier movement.",
        "Craft a movement that responds directly to the last gesture.",
        "Present an action that acknowledges what was just done.",
        "Compose a response action that interacts with the previous motion.",
        "Prepare a movement that follows up on the last action.",
        "Devise a gesture that addresses the previous movement.",
        "Respond with an action that connects to the last gesture.",
        "Perform a motion that engages with the earlier action.",
        "Create a response action that aligns with the last movement.",
        "Articulate a movement that reflects on the previous gesture.",
        "Generate an action that reacts to the last motion.",
        "Craft a gesture that engages with the previous actions.",
        "Deliver a response action that acknowledges the last movement.",
        "Compose an action that follows the earlier gesture.",
        "Prepare a movement that addresses the previous action.",
        "Devise a response through an action that connects to the last gesture.",
        "Perform an action that interacts with what was just done.",
        "Create a gesture that reflects the last person's motion.",
        "Present a movement that responds to the earlier action.",
        "Articulate a response action that engages with the last motion.",
        "Generate an action that acknowledges the previous movement.",
        "Craft a gesture that reacts to the last action taken.",
        "Deliver a response that follows the previous motion.",
        "Compose a movement that acknowledges the earlier gesture.",
        "Prepare an action that responds to what was just done.",
    ],
    
}